  
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Allow http on firewall
  command: firewall-cmd --permanent --add-service=https --add-service=http

- name: Reload Firewall
  command: firewall-cmd --reload
  
